### ISSUE TITLE
HTML in translation string

### ISSUE THREAD

**Issue by stefan-holzapfel-azm** [andreasbm/lit-translate#13]
Hi!

I sometimes have simple HTML in my translations strings. E.g. line breaks or if I want to give the translator/editor the possibility to mark a word as `<strong>`. 

Maybe that is not a good practice at all (?), but that's how it is handled in my project atm.

Is it possible to tell lit-html to render this embedded html?

The unsafHTML directive is not working properly since the translate directive itself returns a lambda. If I pass the result of .get() into unsafeHTML, I lose reactivity/auto-update. Manually requesting updates on language change seems a bit cumbersome.

Any ideas or anything I missed? :)

Thank you!

**Comment by andreasbm** [comment]
Thanks for opening this issue! v1.2.0 was just released and contains the new `translateUnsafeHTML` directive that should be able to do the trick 👍
