### ISSUE TITLE
Building and bundling for production

### ISSUE THREAD

**Issue by lawlesscreation** [andreasbm/lit-translate#29]
Hi, I'm trying to understand how to include the locale JSON files when building for production.

Let's assume we wanted to build and publish a library of web component built using lit-translate to NPM - would the approach to be to include the locale JSON files and the consuming application has to handle the fetching and loading of those JSON files?

__Or__ is the assumption that the package would fetch and register the JSON locale files itself (or be imported) so that a consuming application doesn't have to do anything? I couldn't see any documentation around this approach so I assume that's not recommended?

I can see pros and cons to both but I wondered what the assumption was around how lit-translate should be used building lit-elements for production. It would be nice if, when consuming a web component (or library bundle) that used lit-translate, the application didn't need to worry about fetching or registering the locale JSON files.

I couldn't find any documentation (unless I missed it) around how to build for production when using lit-translate.

Thanks.

**Comment by lawlesscreation** [comment]
After having a closer look at the [demo](https://codepen.io/andreasbm/pen/MWWXPNO?editors=1010) I realised I can do this (rather than using the fetch API):
```
import * as deDE from './i18n/de-DE.json';
import * as enGB from './i18n/en-GB.json';

// Register the translate config
registerTranslateConfig({
    loader: lang => new Promise<any>((resolve, reject) => {
        switch (lang) {
            case 'de-DE':
                resolve(deDE['default']);
                break;
            case 'en-GB':
                resolve(enGB['default']);
        }

        reject(new Error(`The language ${lang} is not supported`));
    })
});
```

Not sure if it's a recommended approach, but it works to bundle up the translation files into the web component package.

**Comment by andreasbm** [comment]
Sorry for not responding before now. It's a very valid use case you have that I think `lit-translate` could support better in the future. For now I think your solution looks good - if the consuming application would like to change or extend the localisation files themselves they would be able to handle the fetching and loading in the application layer. When I get the time I'll add some documentation about this use-case and try make `lit-translate` support it better in the future.
