### ISSUE TITLE
Problem with translate

### ISSUE THREAD

**Issue by e1imba** [andreasbm/lit-translate#40]
Hello, 

I am trying to use lit-translate for my application but it is not working. I saw similar issues ( https://github.com/andreasbm/lit-translate/issues/6 , https://github.com/andreasbm/lit-translate/issues/31 ) but I did not manage to solve my problem.

I am always getting : `(part) => { partCache.set(part, cb); updatePart(part, cb); }`

Result of my `npm ls lit-html` is: 
![image](https://user-images.githubusercontent.com/44132041/162673302-68f8b4ea-1bbb-4d45-9b97-60fdd4f43cbf.png)

And this is my code: 

![image](https://user-images.githubusercontent.com/44132041/162674340-12ee044f-53ed-409e-9227-73147ec9ab38.png)

And en.json is pretty simple: 

![image](https://user-images.githubusercontent.com/44132041/162674490-3d7fe15d-adf3-44e1-bb02-805c2a48c536.png)

Also, when I try to open [codepen ](https://codepen.io/andreasbm/pen/MWWXPNO?editors=1010)project from description, it is showing me same error.

**Comment by christophe-g** [comment]
Have you installed `lit-translate@next` ? 

https://github.com/andreasbm/lit-translate/issues/22#issuecomment-890503937

**Comment by christophe-g** [comment]
@e1imba - happy it is working for you

@runem, @andreasbm - any chance to publish @next as @v2 so that this type of situation is avoided for new users ?

**Comment by andreasbm** [comment]
Sorry for not responding before now. 

@christophe-g I've published `lit-translate@2.0.0` that supports v2 of lit so new users shouldn't face the confusion anymore.

I've also updated the [playground](https://codepen.io/andreasbm/pen/MWWXPNO) to support v2.

Let me know if you should have any problems and I'll reopen this issue.

**Comment by christophe-g** [comment]
Great, thanks !
