### ISSUE TITLE
Translations including html

### ISSUE THREAD

**Issue by davidsteinberger** [andreasbm/lit-translate#9]
First, awesome lib. Thank you!

I want to use [intl-messageformat](https://www.npmjs.com/package/intl-messageformat) to interpolate messages. So I set an interpolation function:

```
registerTranslateConfig({
  loader: (lang: string) => fetch(`/i18n/${lang}.json`).then(res => res.json()),
  interpolate: (text: string, values: {[key: string]: string}) => {
    const msg = new IntlMessageFormat(text, __locale || defaultLocale);
    return msg.format(values);
  },
});
```

It's probably not very smart, b/c I'm not reusing msg instances, but hey it works.

What I'm struggling with is, that when `msg.format(values)` returns html I can't put this unsafely into my component with the `translate` directive.  
Now I know that `unsafeHTML` and the like should be used with caution, but in my specific case I think it's justified. Do you have any idea how I could accomplish this?

**Comment by andreasbm** [comment]
Hi David, thanks for opening this issue 👍If there are no user data involved in the interpolation I would go for `unsafeHTML` as you suggest. I'm very excited about the use-case you are presenting (adding Intl to the interpolation function) so I came up with a suggestion on how I would implement it myself. If you want to play around with it yourself you can find it [here](https://codepen.io/andreasbm/pen/GRRGwJp?editors=1010) ☀️ 

```javascript
// Register the translate config with a loader and an interpolate function. 
registerTranslateConfig({
  loader: lang => {
    switch (lang) {
      case "en-US":
        return {
          photos: `<b>You</b> have {numPhotos, plural, =0 {no photos.}=1 {one photo.}other {# photos.}}`
        };
    }

    throw new Error(`The language ${lang} is not supported..`);
  },
  
  // Use the "intl-messageformat" library for formatting.
  interpolate: (text, values, config) => {
    const msg = new IntlMessageFormat(text, config.lang);
    return msg.format(extract(values));
  },
});

class MyApp extends LitElement {
  connectedCallback() {
    super.connectedCallback();

    // Load the en-US strings and update the component
    use("en-US").then(() => this.requestUpdate());
  }

  render() {
    return html`
      <p>${unsafeHTML(get("photos", {numPhotos: 0}))}</p>
      <p>${unsafeHTML(get("photos", {numPhotos: 1}))}</p>
      <p>${unsafeHTML(get("photos", {numPhotos: 5}))}</p>
    `;
  }
}

customElements.define("my-app", MyApp);
```

**Comment by davidsteinberger** [comment]
Thanks. I tried 2 approaches. The first one was very similar to the one you mentioned above. While this works, I'm then missing the awesomeness of the translate directive. My other attempt was then to recreate the translate directive and use the same approach as used within [unsafeHTML](https://github.com/Polymer/lit-html/blob/06f6eead073990235861db3be23dfcd412b331b0/src/directives/unsafe-html.ts#L49-L51) to set the value.
